chore: add page for tracking Borceux progress
the1lab/1lab pull request #402
Opened 2024-06-30 13:46 UTC by TOTBWF

# Description

Adds a page for tracking progress on Borceux. Somewhat surprisingly, we are already 34% of the way done!

## Checklist

Before submitting a merge request, please check the items below:

- [x] I've read [the contributing guidelines](https://github.com/plt-amy/1lab/blob/main/CONTRIBUTING.md).
- [x] The imports of new modules have been sorted with `support/sort-imports.hs` (or `nix run --experimental-features nix-command -f . sort-imports`).
- [x] All new code blocks have "agda" as their language.

If your change affects many files without adding substantial content, and
you don't want your name to appear on those pages (for example, treewide
refactorings or reformattings), start the commit message and PR title with `chore:`.

2024-06-30 13:56 UTC, Lavenza commented
[Pull request preview](https://preview.1lab.dev/402)

2024-07-01 19:02 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * h. ❌
Do we need these trailing :x:?

2024-07-02 14:25 UTC, TOTBWF commented on src/Borceux.lagda.md
> +  * h. ❌
I find it useful to know what hasn't been done so that I know what to work on; I'm open to other emojis though!

2024-07-02 14:36 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * h. ❌
Wouldn't it be better to have these in a todo list in an issue or something?

2024-07-02 14:38 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * h. ❌
Or a [project](https://github.com/plt-amy/1lab/projects?query=is%3Aopen)

2024-07-02 15:41 UTC, TOTBWF commented on src/Borceux.lagda.md
> +  * h. ❌
Fair enough; I'll open a project and take some times to categorize things a bit more

2024-07-23 12:24 UTC, plt-amy commented on src/Borceux.lagda.md
> +Borceux uses some outdated terminology here , and also uses a condition
```suggestion
Borceux uses some outdated terminology here, and also uses a condition
```

2024-07-23 12:29 UTC, plt-amy commented on src/Borceux.lagda.md
> +* Examples 2.1.7:
Should this still be here?

2024-07-23 12:42 UTC, plt-amy requested changes

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * a. `Hom[-,-]`
```suggestion
  * a. `Hom[-,-]`{.Agda}
```

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +* Exercise 1.11.1: 🚧 `thin-functor`{.Agda}
broken link

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +* Exercise 1.11.8: 🚧 `Curry`{.Agda}, `Uncurry`{.Agda}
broken link

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * 1. `pasting-left→outer-is-pullback`{.Agda}
broken link

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * a. `Sets-pullbacks`{.Agda}
broken link

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +* Exercises 2.17.8: `extend-is-colimit`{.Adga}, `is-colimit-restrict`{.Agda}
```suggestion
* Exercises 2.17.8: `extend-is-colimit`{.Agda}, `is-colimit-restrict`{.Agda}
```

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +* Definition 3.4.4: `is-equivalence`{.Adga}
```suggestion
* Definition 3.4.4: `is-equivalence`{.Agda}
```

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * (1 ⇒ 2) `adjoint→is-lan-id`{.Agda}, `adjoint→is-absolute-lan`{.Agda}
first link here is broken

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * (⇐) `right-adjoint→objectwise-rep`
```suggestion
  * (⇐) `right-adjoint→objectwise-rep`{.Agda}
```

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  2. `o⊥m`
```suggestion
  1. `m⊥o`{.Agda}
  2. `o⊥m`{.Agda}
```

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * 3. `in-intersection≃is-iso`{.Agda}
broken link

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +* Example 8.2.4: `ConstO`{.Agda}, `const-nato`{.Agda}
`const-nato` is missing

2024-07-23 12:42 UTC, plt-amy commented on src/Borceux.lagda.md
> +  * d. `const-nt`{.Agda}
this one's missing too

2024-07-25 23:55 UTC, plt-amy approved these changes

2024-07-26 00:13 UTC, merged