wip: elementary topos nonsense
the1lab/1lab pull request #411
Opened 2024-07-19 20:10 UTC by plt-amy

watch this space but not too closely

2024-07-19 20:16 UTC, Lavenza commented
[Pull request preview](https://preview.1lab.dev/411)

2024-07-19 20:16 UTC, plt-amy commented
oh, she's alive!

2025-01-10 19:54 UTC, plt-amy commented
I guess what's here is mostly done, there's just not a lot of it

2025-03-07 21:54 UTC, TOTBWF requested changes
Looks great, only have a couple of minor nits.

It would also be cool to prove that the displayed category of subobjects has a skeletal generic object iff it has a subobject classifier, but that could be done in a separate PR.

2025-03-07 21:54 UTC, TOTBWF commented on src/Cat/Instances/Sheaf/Omega.lagda.md
> +First, suppose that the domain of $A' \mono A$ is indeed a sheaf. First,
Two "First,"s in a row.

2025-03-07 21:54 UTC, TOTBWF commented on src/Cat/Instances/Sheaf/Omega.lagda.md
> +each of the resulting sieves is closed. To this end, susppose we have
```suggestion
each of the resulting sieves is closed. To this end, suppose we have
```

2025-03-08 14:30 UTC, plt-amy commented on src/Cat/Instances/Presheaf/Limits.lagda.md
> +  clo : ∀ {ℓs} (c : ⌞ C ⌟) → Functor (Sets ℓs) (PSh (ℓs ⊔ ℓ) C)
:stuck_out_tongue:

2025-03-08 14:30 UTC, plt-amy commented on src/Cat/Instances/Sheaf/Omega.lagda.md
> +First, suppose that the domain of $A' \mono A$ is indeed a sheaf. First,
why after you're done assuming the other thing is the new first thing to do!

2025-03-11 15:42 UTC, TOTBWF submitted a review, later dismissed

2025-03-17 22:59 UTC, TOTBWF approved these changes

2025-03-17 23:13 UTC, merged