Added (homotopy) Pushouts and Cocones, and some features/examples of said.
the1lab/1lab pull request #418
Opened 2024-07-27 09:34 UTC by jake-87

# Description

Added (homotopy) Pushouts and Cocones, and some features/examples of said.

This PR is almost certainly not perfect - I have tried my best to match the existing code and similar, and likewise have tried my best to write good quality prose, but I'm leaving this a WIP until I'm confident in the quality of work.

In the meantime though, review/critique is much appreciated.

## Checklist

Before submitting a merge request, please check the items below:

- [x] I've read [the contributing guidelines](https://github.com/plt-amy/1lab/blob/main/CONTRIBUTING.md).
- [x] The imports of new modules have been sorted with `support/sort-imports.hs` (or `nix run --experimental-features nix-command -f . sort-imports`).
- [x] All new code blocks have "agda" as their language.

If your change affects many files without adding substantial content, and
you don't want your name to appear on those pages (for example, treewide
refactorings or reformattings), start the commit message and PR title with `chore:`.

2024-07-27 11:04 UTC, Lavenza commented
[Pull request preview](https://preview.1lab.dev/418)

2024-08-02 21:26 UTC, TOTBWF reviewed
Thanks for the contribution! Just a couple of minor formatting nits :)

2024-08-02 21:26 UTC, TOTBWF commented on src/Homotopy/Pushout.lagda.md
> +## The Universal property of a pushout, via Cocones
Universal should be lowercase here.

2024-08-02 21:26 UTC, TOTBWF commented on src/Homotopy/Pushout.lagda.md
> +Pushout→E≡CoconeE = ua ( Pushout→Cocone , is-iso→is-equiv iso-pc ) where
We should probably remove redundant spaces here. Also, maybe this should be `Pushout-universal-cocone` or something?

2024-08-03 10:08 UTC, jake-87 commented on src/Homotopy/Pushout.lagda.md
> +Pushout→E≡CoconeE = ua ( Pushout→Cocone , is-iso→is-equiv iso-pc ) where
Hm, which spaces are you referring to? The newline could be removed, but are you also referring to others?

2024-08-03 10:15 UTC, jake-87 commented
Sorry about that commit sleugh, I'm happy to squash them if wanted.

2024-08-03 10:42 UTC, ncfavier requested changes

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +The **Pushout** of this span is defined as the higher inductive type
```suggestion
The **pushout** of this span is defined as the higher inductive type
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +```agda
```suggestion
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +```agda
```suggestion
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +	\arrow["{\rm{inl}}", from=1-3, to=3-3]
```suggestion
	\arrow["{\rm{inr}}", from=1-3, to=3-3]
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +## Suspensions as Pushouts
```suggestion
## Suspensions as pushouts
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +`Pushout`{.Agda} of, for some type `A`, the span `⊤ ← A → ⊤`{.Agda}:
```suggestion
The [[suspension]] of a type $A$ can be expressed as the `Pushout`{.Agda}
$\top \ot A \to \top$:
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +	\arrow["{\rm{inl}}", from=1-3, to=3-3]
```suggestion
	\arrow["{!}", from=1-1, to=1-3]
	\arrow["{!}"', from=1-1, to=3-1]
	\arrow["{\rm{inr}}", from=1-3, to=3-3]
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +or equivalently `inl ≡ inr`{.Agda}.
```suggestion
`merid`{.Agda}.
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +
```suggestion
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +```agda
```suggestion
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +## The universal property of a pushout, via Cocones
```suggestion
## The universal property of pushouts
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +To formulate the universal property of a pushout, we first introduce the **Cocone**.
```suggestion
To formulate the universal property of a pushout, we first introduce **cocones**.
```

2024-08-03 10:42 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +```
These are unused in the code: replace them with inline math.

2024-08-03 11:00 UTC, jake-87 commented
Thank you - I'll take that as a general comment that my writing style was too "informal", I suppose?

2024-08-03 11:00 UTC, ncfavier commented on src/Homotopy/Pushout.lagda.md
> +`h : (c : C) → i (f c) ≡ j (g c)`{.Agda}, forming:
```suggestion
consists of functions $i : A \to D$, $j : B \to D$, and a homotopy
$h : (c : C) \to i (f c) \is j (g c)$, forming:
```

2024-09-22 01:11 UTC, jake-87 commented
Hi @ncfavier - is there anything else you'd like me to change?

2024-09-23 09:03 UTC, ncfavier approved these changes

2024-09-23 09:06 UTC, merged